export { default as showMessage } from '@/utils/showMessage'
export { default as getComponentRootDom } from '@/utils/common/getComponentRootDom'
export { default as formDate } from '@/utils/formDeta'
export { default as debounce } from '@/utils/debounce'
export { default as titleContoller } from '@/utils/setTitleContoller'
export { default as getPageComponent } from '@/utils/progress'